name: tokumemo_plus
description: A new Flutter project.
# 公開パッケージにしないためのコード
publish_to: 'none'

# バージョン番号+ビルド番号
version: 1.0.0+1

environment:
  # dart-sdkのバージョンを指定($ flutter doctor -v で使用しているバージョンを確認可能  Dart version x.x.x)
  sdk: '>=3.1.5 <4.0.0'

# パッケージ追加($ flutter pub upgrade --major-versions で更新できる)
# 依存関係の新バージョン確認は$ flutter pub outdated
dependencies:
  flutter:
    sdk: flutter
  # iOSスタイルのアイコンで共に使用
  cupertino_icons: ^1.0.2

  # Riverpod
  flutter_riverpod:
  # 機能は最小限に。必要な時に使用
  hooks_riverpod:

  # Transition
  page_transition:

  # LocalDatabase
  shared_preferences:

  # Navigation
  go_router: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Static analysis
  # 静的解析ツール
  pedantic_mono:
# 後々実装したい、https://zenn.dev/minedia/articles/61a9a107211422
#  custom_lint:
# 後々実装したい、https://blog.dalt.me/3697
#  riverpod_lint:

flutter:
  # material Iconsクラスのアイコンを使用できる
  uses-material-design: true

  # imagesの読み込み先を指定
#  assets:
#    - assets/images/
