name: tokumemo_plus
description: A new Flutter project.
# 公開パッケージにしないためのコード
publish_to: 'none'

# バージョン番号+ビルド番号
version: 1.0.0+1

environment:
  # dart-sdkのバージョンを指定($ flutter doctor -v で使用しているバージョンを確認可能  Dart version x.x.x)
  sdk: '>=3.1.5 <4.0.0'

# パッケージ追加($ flutter pub upgrade --major-versions で更新できる)
# 依存関係の新バージョン確認は$ flutter pub outdated
dependencies:
  flutter:
    sdk: flutter
  # iOSスタイルのアイコンで共に使用
  cupertino_icons: ^1.0.2

  # Riverpod
  flutter_riverpod:
  # 機能は最小限に。必要な時に使用
  hooks_riverpod:

  # Transition
  page_transition:

  # LocalDatabase
  shared_preferences:

  # Navigation
  go_router: ^12.1.1

  # 起動画面(表示設定はpubspec.yaml内の下部にある)
  flutter_native_splash:
  dio: ^5.4.0
  retrofit: ^4.0.3
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # アプリアイコン生成
  flutter_launcher_icons:

  # Static analysis
  # 静的解析ツール
  pedantic_mono:
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
# 後々実装したい、https://zenn.dev/minedia/articles/61a9a107211422
#  custom_lint:
# 後々実装したい、https://blog.dalt.me/3697
#  riverpod_lint:

flutter:
  # material Iconsクラスのアイコンを使用できる
  uses-material-design: true

  # imagesの読み込み先を指定
  assets:
    - assets/images/

# 変更を加えたら次のコードで起動画面を生成して反映する必要がある
# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: '#FFFFFF'
  image: 'assets/images/tokumemo_logo.png'
  fullscreen: true

# 変更を加えたら次のコードでアイコンを生成して反映する必要がある
# flutter pub run flutter_launcher_icons:main
# AndroidはAppIconが起動画面に表示されるため、オレンジ枠線部分を削除したい
# アイコンサイズ：iOS[1024×1024],Android[512×512]
flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/tokumemo_logo.png"
  image_path_ios: "assets/images/tokumemo_icon.png"
